### ISSUE TITLE
Optimization flags

### ISSUE THREAD

**Issue by 4sfaloth** [guikarist/tensorflow-windows-build-script#10]
How can I set the optimization flags (eg: avx2) when using this script to build tensorflow?
I tried adding "--copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2" to the string fed to BazelBuildParameters but then at build time I had lots of warning saying they were unknown options.

I realize the script prompts you about this at some time (giving arch:/avx or something like that as an example) but I am unsure on how to structure the answer

**Comment by Steroes** [comment]
You can always set the environment variable manually in the script like this:
`$ENV:CC_OPT_FLAGS="/arch:AVX2"`

**Comment by 4sfaloth** [comment]
@Steroes thanks. Would it be the same for all the others? So I'd add to the beggining of the script
$ENV:CC_OPT_FLAGS="/arch:AVX"
$ENV:CC_OPT_FLAGS="/arch:AVX2"
$ENV:CC_OPT_FLAGS="/arch:FMA"
$ENV:CC_OPT_FLAGS="/arch:FPMATH=BOTH"
$ENV:CC_OPT_FLAGS="/arch:MSSE4.2"
?

**Comment by guikarist** [comment]
It has nothing to do with this script that your flags were unknown. Some of them were unknown when I built Tensorflow step by step. `$BazelBuildParameters` can get every flag which is accepted by Bazel building Tensorflow. However, I didn't find the full list of the available flags.

On the other hand, there are many environment variables that can be set before building, by which you  can make the building process completely automatic. I recommend you declare them before running the script.

**Comment by Steroes** [comment]
> @Steroes thanks. Would it be the same for all the others? So I'd add to the beggining of the script
> $ENV:CC_OPT_FLAGS="/arch:AVX"
> $ENV:CC_OPT_FLAGS="/arch:AVX2"
> $ENV:CC_OPT_FLAGS="/arch:FMA"
> $ENV:CC_OPT_FLAGS="/arch:FPMATH=BOTH"
> $ENV:CC_OPT_FLAGS="/arch:MSSE4.2"
> ?

No, now you overwrite the variable every time and only the last one will be used. I am not sure if you can add multiple at once in the variable. @guikarist Do you know this?

**Comment by guikarist** [comment]
@Steroes I don't know `$ENV:CC_OPT_FLAGS`. But what you said is obviously right.

**Comment by guikarist** [comment]
Closed due to inactivity.
