### ISSUE TITLE
Build ignores the symbols of tf_exported_symbols_msvc.lds

### ISSUE THREAD

**Issue by subavicky** [guikarist/tensorflow-windows-build-script#11]
Thanks for the Script. I am able to build the libtensorflow_cc.so, rename dll and lib and find the missing symbols. But when I try to add it to tf_exported_symbols_msvc.lds and build again, I am getting this error.

**warning LNK4017: ?GetVarint32PtrFallback@core@tensorflow@@YAPEBDPEBD0PEAI@Z statement not supported for the target platform; ignored**

**Comment by Steroes** [comment]
Can you post the complete linker error that comes from your missing symbols?
It could also have to do something with 32/64 bits difference. What is your VisualStudio project configuration?

**Comment by guikarist** [comment]
Same as #3. You should build with `x64` configuration in Visual Studio.

**Comment by subavicky** [comment]
I tried with all the four combinations of architecture(x64, x86) and the build type(Release, Debug). Every time I get the same error.

**Comment by guikarist** [comment]
Do you mean you have tried to build TF without this symbol, but with all other missing symbols, and then you could not build successfully in VS?

**Comment by subavicky** [comment]
No. During my build in VS, I got only one linker error which says "undefined symbol ?GetVarint32PtrFallback@core@tensorflow@@YAPEBDPEBD0PEAI@Z".

When I tried to add this symbol to  tf_exported_symbols_msvc.lds and build the tensorflow again using the script, I got the above warning which essentially says it is ignoring the symbol and building with it.

**Comment by Steroes** [comment]
Are you sure you are building libtensorflow_cc.so and not libtensorflow.so?

**Comment by guikarist** [comment]
Closed due to inactivity.
