### ISSUE TITLE
Using dll

### ISSUE THREAD

**Issue by ttdd11** [guikarist/tensorflow-windows-build-script#13]
This has been very helpful thanks for the great work.

Previously I've built tensorflow in C++ and had to move away from that method for compatibility reasons.

I've followed the instructions and have the .lib and dll. How do I use these now? Really all I would like to do is load a graph and run a session, however I get errors when included files required to do this. 

Any help here would be greatly appreciated.

Just to follow up: it looks like you run extract-built-tensorflow-cpp-api.ps1, link the lib and add the source files to the include path of the project. Is this the correct process?

**Comment by guikarist** [comment]
Correct for versions less than or equal to 1.12.0.

**Comment by guikarist** [comment]
> Correct for versions less than or equal to 1.12.0.

BYW, the latest version of Tensorflow with new building API has been tested and I will commit new version of script recently.

**Comment by ttdd11** [comment]
Thanks for this.

After copying the source code I get errors when using the following includes:

#include <tensorflow/core/framework/graph.pb.h>
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/public/session_options.h>

First error is a too many include issue from Tensor in eigen. After putting header guard, there are many more errors. I think I've made a mistake somewhere as there are no .pb.h files in the sources which are included everywhere.

Have you had this happen before?

**Comment by guikarist** [comment]
> First error is a too many include issue from Tensor in eigen. After putting header guard, there are many more errors. I think I've made a mistake somewhere as there are no .pb.h files in the sources which are included everywhere.

I have encountered this. It is something about setting but I am sorry I have forgotten what I did.

> Ideally I would like to build a single header that calls into the lib with the exported symbols from the build. Is this the correct process?

Sorry I don't understand this.

**Comment by ttdd11** [comment]
A settings in the bazel the build? What did you use for these:

Do you wish to build TensorFlow with Apache Ignite support?
Do you wish to build TensorFlow with XLA JIT support?
Do you wish to build TensorFlow with ROCm support?
Do you wish to build TensorFlow with CUDA support?
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:

**Comment by guikarist** [comment]
> A settings in the bazel the build? What did you use for these:
> 
> Do you wish to build TensorFlow with Apache Ignite support?
> Do you wish to build TensorFlow with XLA JIT support?
> Do you wish to build TensorFlow with ROCm support?
> Do you wish to build TensorFlow with CUDA support?
> Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
> Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:

I didn't set this because I thought they varied a lot between versions. However, I have a plan to do this.

**Comment by ttdd11** [comment]
Okay great. In your bazel gen files do you have the file graph.pb.h?

**Comment by guikarist** [comment]
Oops. I think I misunderstand [your comment](https://github.com/guikarist/tensorflow-windows-build-script/issues/13#issuecomment-469680400).

My setting is N, N, N, Y, "/arch:AVX", Y. However, IMO there should be no problem here in your setting.

> Okay great. In your bazel gen files do you have the file graph.pb.h?

Yes. But it is built by latest Tensorflow master version of C API.

**Comment by ttdd11** [comment]
Okay I'll re-run the c++ api and see if the files are generated. If not perhaps I could build the c api as well, copy the gen files form the and use them in the c++ api. Do you see a problem with that? I don't really care whether I use the c++ or c api, however in the c api I was struggling to set the device to a particular gpu and load an image into my graph.

**Comment by ttdd11** [comment]
I'll keep playing around with this either way and see if I can provide some further instructions if I get it to work.

**Comment by guikarist** [comment]
> Okay I'll re-run the c++ api and see if the files are generated. If not perhaps I could build the c api as well, copy the gen files from the build and use them in the c++ api. Do you see a problem with that? I don't really care whether I use the c++ or c api, however in the c api I was struggling to set the device to a particular gpu and load an image into my graph.

I have been working on a refactoring of the script. You may use the present script to build the latest C API by following steps.

1. Correct `$bazelVersion = "0.19.0"` to `$bazelVersion = "0.20.0"` at line 100 in the script.
    * If your Bazel version is not `0.20.0`, you should uninstall it.
1. Substitute your old building API with one of [these ones](https://github.com/tensorflow/tensorflow/pull/24963).
1. Do what you did when building C API.

However I have no ideas on how to use these built things. Good luck!

**Comment by guikarist** [comment]
> I'll keep playing around with this either way and see if I can provide some further instructions if I get it to work.

Waiting your sharing!

**Comment by ttdd11** [comment]
@guikarist I'm looking at the scipt for v 1.3.1. Do we not need to run the cpp patches and such for this version? In build.ps1 the later patches and symbols don't apply to it.

**Comment by guikarist** [comment]
Yes, we need to do that but I didn't have time to test it. It will be nice of you to test it and commit the patch for `v1.13.1` if necessary.

**Comment by ttdd11** [comment]
@guikarist okay I will work on this. How do I add an addional patch (https://github.com/tensorflow/tensorflow/pull/17767/files)

**Comment by guikarist** [comment]
There is a `create new file` button at repo home.

**Comment by guikarist** [comment]
@ttdd11 Have you tested?

**Comment by ttdd11** [comment]
I have but the monolithic build still has issues with string memory sharing. I think the devs are trying to fix it but now sure.

**Comment by guikarist** [comment]
We should talk about this topic on #15.

**Comment by guikarist** [comment]
The topic of this issue seems to be over.
