### ISSUE TITLE
Test for C++ API of v1.13.1

### ISSUE THREAD

**Issue by guikarist** [guikarist/tensorflow-windows-build-script#15]
The C++ API of `v1.13.1` has not been tested.

**Comment by guikarist** [comment]
@ttdd11 So does it need to apply C++ patches on `v1.13.1`?

**Comment by guikarist** [comment]
@kevinLu1114 So there seems to symbol issues in 1.13.1 too. Try same paradigm of the patch for 1.12.0. Then please push a PR, thx!

**Comment by guikarist** [comment]
@asbe @Steroes @kevinLu1114 @ihuale 

Ok, the symbol patch for `v1.13.1` is created at de2e3bba1cfe7e78b3283cbdbb5698551f8909a4 which needs testing.

**Comment by guikarist** [comment]
@asbe @Steroes @kevinLu1114 @ihuale
Anyone tested?

**Comment by asbe** [comment]
Seems to build correctly uncer VS2017, but I have to add more symbols to the patch to get my test code (simple matrix multiplication) to link. Still cycling through rebuilding dll, finding missing symbols, rebuilding etc. Any reason why we cannot use an EXP file as linker input instead?

**Comment by guikarist** [comment]
So now added symbols work?

I don’t know what exp file is. What does it do?

**Comment by asbe** [comment]
@guikarist Can report success using DLL - but had to add more symbols. I now have a 35MB binary that does 2x2 matrix multiplication ;-)

The exp or export file should provide the symbols needed for linker

**Comment by guikarist** [comment]
So we can say `v1.13.1` is tested.

Closed
