### ISSUE TITLE
tf 1.13.1 python error

### ISSUE THREAD

**Issue by kevinLu1114** [guikarist/tensorflow-windows-build-script#17]
![未命名](https://user-images.githubusercontent.com/45491278/55237149-68d13f00-526c-11e9-993b-8397cc778237.png)

pyvenv.cfg:
``
home = D:\Anaconda
include-system-site-packages = false
version = 3.7.1
``

I use command ``--config=opt--config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package``

**Comment by guikarist** [comment]
It seems an issue of SSL module during installation of pip packages. You should search that SSLError in Google, which is not related to this repo.
