### ISSUE TITLE
Building the wheel fails

### ISSUE THREAD

**Issue by Scorillo47** [guikarist/tensorflow-windows-build-script#20]
After succesful bazel build, I followed Python wheel build instructions per wiki and I get a failure:

F:\_git\tensorflow-windows-build-script\source>bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg
/bin/bash: bazel-bintensorflowtoolspip_packagebuild_pip_package: No such file or directory

**Comment by Scorillo47** [comment]
Found a solution, actually
1) start C:\msys64\mingw64.exe
2) cd /f/_git/tensorflow-windows-build-script/source
3) bazel-bin/tensorflow/tools/pip_package/build_pip_package ../out

**Comment by guikarist** [comment]
The issue is closed due to solved.
