### ISSUE TITLE
Is there a way to provide an answers file? 

### ISSUE THREAD

**Issue by Scorillo47** [guikarist/tensorflow-windows-build-script#22]
Hi all,

This script is great but wanted to have an option to submit a certain configuration automatically. Is there a way to do this? 

For instance I want to provide a certain non-default answer to questions asked (CUDA enabled? yes, etc) 

Tried to redirect an answers text file to Powershell but doesn't seem to work.

**Comment by Steroes** [comment]
You can set these configurations also in environment variables with PowerShell, e.g.:
```
$ENV:TF_NEED_GCP=0
$ENV:TF_NEED_CUDA=0
$ENV:TF_NEED_AWS=0
$ENV:TF_NEED_JEMALLOC=0
$ENV:TF_NEED_HDFS=0
$ENV:TF_NEED_KAFKA=0
$ENV:TF_ENABLE_XLA=0
$ENV:TF_NEED_GDR=0
$ENV:TF_NEED_VERBS=0
$ENV:TF_NEED_NGRAPH=0
$ENV:TF_CUDA_CLANG=0
$ENV:TF_NEED_OPENCL_SYCL=0
$ENV:TF_NEED_MPI=0
$ENV:TF_DOWNLOAD_CLANG=0
$ENV:CC_OPT_FLAGS="/arch:AVX2"
$ENV:TF_SET_ANDROID_WORKSPACE=0
$ENV:TF_OVERRIDE_EIGEN_STRONG_INLINE=1
```
If they are correctly specified for the correct tf version (above is for 1.11) then the script won't even ask for these variables.
The `configure.py` script will tell which variables you can use.

**Comment by guikarist** [comment]
Closed due to a provided workaround
