### ISSUE TITLE
How to build debug version？

### ISSUE THREAD

**Issue by gmt710** [guikarist/tensorflow-windows-build-script#29]
Thank you very much for sharing.I've successfully built release version of tensorflow-v1.12.0 by your suggestion.
But I can't have any correct idea about how to build debug version.I've tried this:

>$parameterString = "-c fastbuild --config=cuda --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings //tensorflow:libtensorflow_cc.so --verbose_failures"

or

>$parameterString = "-c dbg --config=cuda --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings //tensorflow:libtensorflow_cc.so --verbose_failures"

but it gives me this error:
>tensorflow::io::GetTempFilename

I find some reference https://github.com/tensorflow/tensorflow/issues/22338 and https://github.com/tensorflow/tensorflow/issues/24974 .But it also doesn‘t work.

My envoriment like this:
> win10 
>  vs2015                 
> cuda9.0                  
> cudnn7.6              
> python3.5.2                
> tensorflow-v1.12.0              
> bazel0.22.0                
> msys2-x86_64-20190524
         
I've tried it on two machines, but it's all the same.If you or any other can give some suggestions,I'll appreciate it very much.

**Comment by guikarist** [comment]
I am really sorry for not being familiar with what the **debug version** is. Is it something which enables you to debug when using the built Tensorflow?

**Comment by gmt710** [comment]
Yeah.It's perfect to debug for release x64 configuration.But it breaks during debugging by this configuration:

![image](https://user-images.githubusercontent.com/34018741/59658328-ddfe4180-91d5-11e9-9af6-e1765cd87f24.png)


![image](https://user-images.githubusercontent.com/34018741/59658305-d0e15280-91d5-11e9-8387-ed9a7360d7c2.png)

It can not correctly use the tensorflow_cc.dll file.

**Comment by guikarist** [comment]
Is it possible to debug with **release version**?

**Comment by gmt710** [comment]
Okay,If you have any idea or suggestion about **debug version**, please let me know, OK?Thank you very much!!!

**Comment by guikarist** [comment]
Fine, however please let me know whether it is possible to debug with **release version**.

**Comment by gmt710** [comment]
It works fine with **release version**.
![image](https://user-images.githubusercontent.com/34018741/59660851-19037380-91dc-11e9-9e8d-14eb80de4025.png)

![image](https://user-images.githubusercontent.com/34018741/59660833-0f7a0b80-91dc-11e9-84da-ed4583e59fc6.png)

**Comment by guikarist** [comment]
I mean debugging like this:

![image](https://docs.microsoft.com/en-us/visualstudio/debugger/media/dbg-tour-set-a-breakpoint.gif)

**Comment by gmt710** [comment]
Oh,It also met this problem.

![image](https://user-images.githubusercontent.com/34018741/59661834-46e9b780-91de-11e9-8772-7f8fc2873be3.png)

**Comment by guikarist** [comment]
Weird. I used to be able to debug. Now I cannot be accessible to my workstation, I would do checks for you in some days.

**Comment by gmt710** [comment]
Thanks for the trouble.

**Comment by Steroes** [comment]
Debug version is known to not work on Window. I get a crash in debug mode when loading a frozen protobuf model, while in release everything works fine. No reason found for this.

**Comment by guikarist** [comment]
> Debug version is known to not work on Window. I get a crash in debug mode when loading a frozen protobuf model, while in release everything works fine. No reason found for this.

@gmt710 This seems to answer your question. So I am about to close this issue.

**Comment by AndreyPlotkinOr** [comment]
I compiled TF v1.10 in debug mode (after several minor code fixes).
Probably something broke down on the way 1.10 -> 1.14.

Anyway, a library in debug mode is essential to solve problems quickly.
There's an option of running release with symbols, but there are situations, when you can't use this mode.

This is a real problem that has to be solved,

**Comment by yuc8939** [comment]
To get rid of this C4716 error, I added `--copt=/w34716` to the bazel build command line, e.g.
`bazel build --copt=/w34716 --experimental_shortened_obj_file_path //moco:moco`
This makes the MSVC compiler happy and I finally have a debug build on Win10!
