### ISSUE TITLE
vs2017 link error

### ISSUE THREAD

**Issue by ymmshi** [guikarist/tensorflow-windows-build-script#3]
First, thanks for your scripts. I follow your steps and built libtensorflowcc.so successfully! But when i use the  libtensorflowcc.so in vs2017,it got two errors.
![default](https://user-images.githubusercontent.com/13198991/51434888-38868680-1ca6-11e9-921c-526aa3a9b427.png)
So I add the  proper symbol into patches\tf_exported_symbols_msvc.lds and rebuild it, but got errors when building.how to solve the link problem

![default](https://user-images.githubusercontent.com/13198991/51434914-e7c35d80-1ca6-11e9-9197-0033259e99a0.png)

I add three symbols as below

`    ?DoMatMul@CudnnSupport@cuda@stream_executor@@UEAA_NPEAVStream@3@AEBV?$DeviceMemory@M@3@1AEBVBatchDescriptor@dnn@3@2PEAV53@@Z
    
?ThenBlasGemm@Stream@stream_executor@@QEAAAEAV12@W4Transpose@blas@2@0_K11MAEBV?$DeviceMemory@M@2@H2HMPEAV52@H@Z
    
?GetVarint32PtrFallback@core@tensorflow@@YAPBDPBD0PAI@Z`

**Comment by guikarist** [comment]
Please give me a text version of your link errors in Visual Studio.

**Comment by ymmshi** [comment]
>           Please give me a text version of your link errors in Visual Studio.

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "char const * __cdecl tensorflow::core::GetVarint32PtrFallback(char const *,char const *,unsigned int *)" (?GetVarint32PtrFallback@core@tensorflow@@YAPBDPBD0PAI@Z)，该符号在函数 "char const * __cdecl tensorflow::core::GetVarint32Ptr(char const *,char const *,unsigned int *)" (?GetVarint32Ptr@core@tensorflow@@YAPBDPBD0PAI@Z) 中被引用	TensorTest	C:\Users\USTC_Lib1010\source\repos\TensorTest\TensorTest\源.obj	1

**Comment by guikarist** [comment]
IMO, you should only add `?GetVarint32PtrFallback@core@tensorflow@@YAPBDPBD0PAI@Z` into `tf_exported_symbols_msvc.lds`.

**Comment by ymmshi** [comment]
I met this error when building
`liblibtensorflow_cc.so.exp : error LNK2001: 无法解析的外部符号 "char const * __cdecl tensorflow::core::GetVarint32PtrFallback(char const *,char const *,unsigned int *)" (?GetVarint32PtrFallback@core@tensorflow@@YAPBDPBD0PAI@Z)
bazel-out/x64_windows-opt/bin/tensorflow/libtensorflow_cc.so : fatal error LNK1120: 1 个无法解析的外部 命令
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 2733.339s, Critical Path: 253.84s
INFO: 3087 processes: 3087 local.
FAILED: Build did NOT complete successfully`

**Comment by guikarist** [comment]
Then what are other three symbols?

**Comment by ymmshi** [comment]
>           Then what are other three symbols?

I met only one link [error](https://github.com/guikarist/tensorflow-windows-build-script/issues/3#issuecomment-455834883) and add only one symbols ` ?GetVarint32PtrFallback@core@tensorflow@@YAPBDPBD0PAI@Z`  into `tf_exported_symbols_msvc.lds`

**Comment by guikarist** [comment]
But you said this:

> I add three symbols as below

**Comment by ymmshi** [comment]
>           But you said this:
> > I add three symbols as below

umm,I delete other two symbols because i misread it

**Comment by guikarist** [comment]
I have tried adding `?GetVarint32PtrFallback@core@tensorflow@@YAPBDPBD0PAI@Z` and `?GetVarint32Ptr@core@tensorflow@@YAPBDPBD0PAI@Z` but failed.

There are some guys with [similiar problem](https://github.com/tensorflow/tensorflow/issues/22338#issuecomment-424924152). But I don't know whether they had imported the symbols properly.

@Steroes Do you have any ideas?

**Comment by guikarist** [comment]
@ymmshi  Have you build solution with `x64` instead of `x86`?

**Comment by ymmshi** [comment]
> @ymmshi Have you build solution with `x64` instead of `x86`?

 how to build with `x64`

**Comment by guikarist** [comment]
Just change this option:
![image](https://user-images.githubusercontent.com/19543014/51471229-188fb980-1db1-11e9-8072-041c4b714077.png)

**Comment by ymmshi** [comment]
a new error "char const * __cdecl tensorflow::core::GetVarint32PtrFallback(char const *,char const *,unsigned int *)" (?GetVarint32PtrFallback@core@tensorflow@@YAPEBDPEBD0PEAI@Z)

**Comment by guikarist** [comment]
Try adding this symbol.

**Comment by ymmshi** [comment]
> Try adding this symbol.

your file include https://github.com/guikarist/tensorflow-windows-build-script/blob/01ffd251b8ab4836e528d6ca80e4d6094a0592cf/patches/tf_exported_symbols_msvc.lds#L11

**Comment by guikarist** [comment]
But you still have the LNK error?

**Comment by ymmshi** [comment]
> But you still have the LNK error?

yes, it's strange!

**Comment by guikarist** [comment]
Update the script, and then do `dumpbin /exports libtensorflow_cc.so` in WSL.

**Comment by guikarist** [comment]
Or follow [this](
https://stackoverflow.com/questions/477387/cannot-find-dumpbin-exe).

**Comment by ymmshi** [comment]
It takes long time for building. So i upload an old one first.[1.txt](https://github.com/guikarist/tensorflow-windows-build-script/files/2781110/1.txt)

**Comment by guikarist** [comment]
I made a [gist](https://gist.github.com/guikarist/e10dff3a4e777856cf40e44713fc2cb7) to instruct you to use the built Tensorflow.

**Comment by guikarist** [comment]
You should link `tensorflow_cc.lib` in Visual Studio. Here is [what you need do](https://stackoverflow.com/a/4446085/10799292).

**Comment by ymmshi** [comment]
I am sorry for troubling you for long time! I have solved this problem just now! The main reason is that I'm too careless, I made a mistake in configuration of VS. In order to get correct step, we must use `Release x64` to build project. I have tried other solution,  it caused lots of errors.

Furthermore, I would like to offer some helps to others. In my project, I need to add symbols below, maybe you can add in `tf_exported_symbols_msvc.lds`.

    `??6tensorflow@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV12@AEBVStatus@0@@Z
    ??1LogMessage@internal@tensorflow@@UEAA@XZ
    ??0LogMessage@internal@tensorflow@@QEAA@PEBDHH@Z
    ?NewSession@tensorflow@@YAPEAVSession@1@AEBUSessionOptions@1@@Z
    ?DebugString@TensorShapeRep@tensorflow@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ`

And I modified the script for extracting built results, maybe other one will need it
[extract-built-tensorflow.ps1.zip](https://github.com/guikarist/tensorflow-windows-build-script/files/2782572/extract-built-tensorflow.ps1.zip)

Thanks for your help again!

**Comment by ymmshi** [comment]
If you want to use tensorflow with opencv, you may need to add `--config=monolithic` to bazel `parameterString`

**Comment by guikarist** [comment]
Glad to know that!
The number of symbols to be exported is limited. So I didn't add every symbol.
And I have compiled with `Debug x64` successfully.

**Comment by guikarist** [comment]
Are you undergraduate?

**Comment by ymmshi** [comment]
> Are you undergraduate?

I am a postgraduate student.

**Comment by guikarist** [comment]
我是6系的，大四，哈工大保研过来的

**Comment by ymmshi** [comment]
> 我是6系的，大四，哈工大保研过来的

牛逼

**Comment by guikarist** [comment]
额。。。

**Comment by ymmshi** [comment]
> 额。。。

加个微信吧

**Comment by guikarist** [comment]
ANDI_Mckee
