### ISSUE TITLE
parameterString question

### ISSUE THREAD

**Issue by tongshiwen** [guikarist/tensorflow-windows-build-script#30]
parameterString : 无法将“parameterString”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包
括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ parameterString = "--config=opt --config=cuda --define=no_tensorflow_ ...
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (parameterString:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by guikarist** [comment]
Missing `$` in the beginning.
