### ISSUE TITLE
build.ps1 error

### ISSUE THREAD

**Issue by tongshiwen** [guikarist/tensorflow-windows-build-script#31]
PS E:\git_tf_build\tensorflow-windows-build-script-master> .\build.ps1  -BazelBuildParameters $parameterString -BuildCpp
API -ReserveSource -ReserveVenv
.\build.ps1 : 无法加载文件 E:\git_tf_build\tensorflow-windows-build-script-master\build.ps1，因为在此系统上禁止运行脚本
。有关详细信息，请参阅 https:/go.microsoft.com/fwlink/?LinkID=135170 中的 about_Execution_Policies。
所在位置 行:1 字符: 1
+ .\build.ps1  -BazelBuildParameters $parameterString -BuildCppAPI -Res ...
+ ~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by guikarist** [comment]
Non-constructive issue.

PLEASE READ [README.md](https://github.com/guikarist/tensorflow-windows-build-script/blob/master/README.md) THOUROUGHLY OR LEARN TO USE GOOGLE. DO NOT WASTE YOUR VALUABLE TIME.
