### ISSUE TITLE
I can't complete the compilation, no error is reported

### ISSUE THREAD

**Issue by x-jeff** [guikarist/tensorflow-windows-build-script#42]
windows10
tensorflow=1.12.0
bazel=0.15.0
CUDA=9
cudnn=7
When I ran the following code:
```
.\build.ps1 `
    -BazelBuildParameters $parameterString `
-BuildCppAPI -ReserveSource –ReserveVenv

```
The compilation process had been stopped here：
![image](https://user-images.githubusercontent.com/43426273/74301137-08b49000-4d8d-11ea-9c54-cf431a926486.png)

At this point, the CPU was no longer working.And there was no error.

I tried to wait for two days, but I still didn't make any progress.

Does anyone know what's going on?

thanks~

**Comment by guikarist** [comment]
What is your `$parameterString` ?

**Comment by terryzhao127** [comment]
What is your `$parameterString` ?

**Comment by x-jeff** [comment]
Thank you for your reply. @guikarist 
I have solved this problem.
refer to [https://github.com/tensorflow/tensorflow/issues/349](https://github.com/tensorflow/tensorflow/issues/349):
Try reducing number of parallel builds by passing '--local_resources 2048,.5,1.0', which would instruct bazel to spawn no more than one compiler process at the time.

here is my $parameterString :

```
$parameterString = "--local_resources 2048,.5,1.0 --config=opt --config=cuda --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings //tensorflow:libtensorflow_cc.so --verbose_failures"
```
