### ISSUE TITLE
How can I build tensorflow C++ API in x86

### ISSUE THREAD

**Issue by woshildh** [guikarist/tensorflow-windows-build-script#45]
Thanks,  I have compiled tensorflow C++ API on window10. But, the tensorflow_cc.dll is x64, it could not be used on my project. Is any methods to build a x86 version? I'm appreciating for your reply.

**Comment by Amuqeet09** [comment]
Did you get any success? I am also looking for tensorflow.dll x86.

**Comment by woshildh** [comment]
Sorry, I could not complie tensorflow in x86 platform.

**Comment by terryzhao127** [comment]
I am so sorry that this script does not provide an option to build Tensorflow in x86. But I found an answer that may be helpful: <https://stackoverflow.com/questions/33634525/tensorflow-on-32-bit-linux>
