### ISSUE TITLE
redistribution of built dll (gpu enabled)

### ISSUE THREAD

**Issue by Keyang** [guikarist/tensorflow-windows-build-script#5]
Hi,
Once I built the dll and I want to redistribute it along with my windows application, do I need pack dependencies like dlls for CUDA / cuDNN to another windows machine which has no CUDA or cuDNN installed?
Or the built dll is enough to run on any machine has a nvidia driver installed?

Thanks,
Keyang

**Comment by guikarist** [comment]
According to [official docs](https://www.tensorflow.org/install/gpu), it is obviously that something like CUDA is always needed, no matter how do you get Tensorflow GPU version.
