### ISSUE TITLE
unrecognized command tar

### ISSUE THREAD

**Issue by 4sfaloth** [guikarist/tensorflow-windows-build-script#7]
First all, awesome work!

I was having some issues with using your script, namely with powershell not being able to use "tar" command (because it was not installed). I noticed the "install tar" part of the script is inside the "if not pacman already installed", is there any reason for this?

I moved it out so as to look like

```powershell
if (! (CheckInstalled pacman)) {
    $version = askForVersion "20180531.0.0"
    choco install msys2 --version $version --params "/NoUpdate /InstallDir:C:\msys64"
    # Install tools that are necessary for buiding.
    pacman -S --noconfirm patch unzip
}

if ($BuildCppProtoBuf) {
	pacman -S --noconfirm tar
}
```

and it seems to be working now. Any reason why tar installation command was inside that if?

**Comment by guikarist** [comment]
Thx. It is a bug and you can make a PR.

**Comment by 4sfaloth** [comment]
I tried to create a branch and push to the repo but seems like I do not have permissions for that; do I need to fork the project for this?

**Comment by guikarist** [comment]
Yes. You can directly edit on my repo and a forked one for you will be generated automatically. After you finish, just make a pull request.

**Comment by guikarist** [comment]
Closed due to merged PR
