### ISSUE TITLE
Build succeds but absl::string_view seems to be missing a method?

### ISSUE THREAD

**Issue by 4sfaloth** [guikarist/tensorflow-windows-build-script#9]
I have succeed in using your script to build tensorflow, and also run the final part of the script by Steroes you mentioned to generated an install directory ready for employment. However, when I try to use tensorflow inside my project (vc140) I get this weird error
"error C2039: 'ends_with': is not a member of 'absl::string_view'"
Looking at string_view.h in fact I cannot see any "ends_with" method. Any idea what the problem is? I am actually unsure of whether this is a build issue (related with the script) or if I should direct this issue to tensorflow repository

**Comment by 4sfaloth** [comment]
Ok nevermind, I was so used to getting build and linking errors for tensorflow I did not realize the "ends_with" call was actually inside my code. It worked with an older version of tensorflow, so I guess the string_view class was changed and dropped it somewhere in the past. All is well!

**Comment by ttdd11** [comment]
@4sfaloth did you build tensorflow_cc.dll? I'm  having a hell of a week trying to get that working in my app.
